Standardise formatting and idioms across all my scripts

diff --git a/git/bin/git-change-email b/git/bin/git-change-email
--- a/git/bin/git-change-email
+++ b/git/bin/git-change-email
@@ -1,23 +1,37 @@
 #!/usr/bin/env bash
-set -e
+set -euo pipefail
 
-if [ -z "$OLD_EMAIL" ]; then
-    echo '$OLD_EMAIL needs to be set'
-    exit 1
+USAGE="
+usage: $(basename "$0") <old_email> <new_email>
+
+Recursively rewrites git history to replace an old email with a new one.
+
+arguments:
+  <old_email>  The email to get rid of
+  <new_email>  The email to replace it with
+"
+
+old_email=${1:-}
+if [ -z "$old_email" ]; then
+  echo >&2 '<old_email> is required!'
+  echo "$USAGE"
+  exit 1
 fi
 
-if [ -z "$NEW_EMAIL" ]; then
-    echo '$NEW_EMAIL needs to be set'
-    exit 1
+new_email=${2:-}
+if [ -z "$new_email" ]; then
+  echo >&2 '<new_email> is required!'
+  echo "$USAGE"
+  exit 1
 fi
 
 git filter-branch --env-filter '
-if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
+if [ "$GIT_COMMITTER_EMAIL" = "$old_email" ]
 then
-    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
+    export GIT_COMMITTER_EMAIL="$new_email"
 fi
-if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
+if [ "$GIT_AUTHOR_EMAIL" = "$old_email" ]
 then
-    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
+    export GIT_AUTHOR_EMAIL="$new_email"
 fi
 ' --tag-name-filter cat -- --branches --tags
diff --git a/tmux/bin/,tmux-sesh b/tmux/bin/,tmux-sesh
--- a/tmux/bin/,tmux-sesh
+++ b/tmux/bin/,tmux-sesh
@@ -1,63 +1,64 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
 EXTRA_FOLDERS=(
-    "$HOME/notes"
-    "$HOME/.dotfiles"
+  "$HOME/notes"
+  "$HOME/.dotfiles"
 )
 
-if ! type tmux &> /dev/null || ! type ghq &> /dev/null; then
-    echo "`ghq` and `tmux` are required" >&2
-    exit 1
+if ! type tmux &>/dev/null || ! type ghq &>/dev/null; then
+  echo >&2 "'ghq' and 'tmux' are required"
+  exit 1
 fi
 
 if [[ -d "$*" ]]; then
-    repo_path="$*"
+  repo_path="$*"
 else
-    for folder in "${EXTRA_FOLDERS[@]}"; do
-        if [[ -d $folder ]]; then
-            repos+="$folder\n"
-        fi
-    done
-
-    repos+=$(ghq list)
-
-    if [[ $# -gt 0 ]]; then
-        repo_href=$(printf "$repos" | fzf -1 -q "$*")
-    else
-        repo_href=$(printf "$repos" | fzf)
+  for folder in "${EXTRA_FOLDERS[@]}"; do
+    if [[ -d $folder ]]; then
+      repos+="$folder\n"
     fi
+  done
 
-    if [[ -z $repo_href ]]; then
-        echo "Couldn't find repo $repo_href" >&2
-        exit 1
-    fi
+  repos+=$(ghq list)
 
-    if [[ $repo_href == /* ]]; then
-        # If the href starts with a slash, assume it's an absolute path
-        # (i.e. from the EXTRA_FOLDERS)
-        repo_path=$repo_href
-    else
-        repo_path=$(ghq list -p -e $repo_href)
-    fi
+  if [[ $# -gt 0 ]]; then
+    repo_href=$(printf "%s" "$repos" | fzf -1 -q "$*")
+  else
+    repo_href=$(printf "%s" "$repos" | fzf)
+  fi
+
+  if [[ -z $repo_href ]]; then
+    echo "Couldn't find repo $repo_href" >&2
+    exit 1
+  fi
+
+  if [[ $repo_href == /* ]]; then
+    # If the href starts with a slash, assume it's an absolute path
+    # (i.e. from the EXTRA_FOLDERS)
+    repo_path=$repo_href
+  else
+    repo_path=$(ghq list -p -e "$repo_href")
+  fi
 fi
 
-repo_name=$(basename $repo_path | sed 's/\.git$//' | sed 's/^\.//' | tr '.' '_')
+repo_name=$(basename "$repo_path" | sed 's/\.git$//' | sed 's/^\.//' | tr '.' '_')
 tmux_running=$(pgrep tmux)
 
 if [[ -z $tmux_running ]]; then
-    # If tmux isn't running, then start tmux with a new session for the repo
-    tmux new-session -s $repo_name -c $repo_path
-    exit 0
+  # If tmux isn't running, then start tmux with a new session for the repo
+  tmux new-session -s "$repo_name" -c "$repo_path"
+  exit 0
 fi
 
-if ! tmux has-session -t=$repo_name 2> /dev/null; then
-    # If tmux doesn't already have a session for the repo, then create it
-    tmux new-session -d -s $repo_name -c $repo_path
+if ! tmux has-session -t="$repo_name" 2>/dev/null; then
+  # If tmux doesn't already have a session for the repo, then create it
+  tmux new-session -d -s "$repo_name" -c "$repo_path"
 fi
 
 # Attach or switch to the session
- if [[ -z $TMUX ]]; then
-     tmux attach -t $repo_name
- else
-     tmux switch-client -t $repo_name
- fi
+if [[ -z "$TMUX" ]]; then
+  tmux attach -t "$repo_name"
+else
+  tmux switch-client -t "$repo_name"
+fi
